const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true, channel:'msedge'});
  const page = await browser.newPage({viewport:{width:1366,height:900}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.PDV_URL || 'http://localhost:3000');
  await page.evaluate(() => { localStorage.clear(); location.reload(); });
  await page.waitForLoadState('load');
  await page.waitForFunction(() => produtosConectados);
  await page.getByRole('button', {name:'Ir para Frente de Caixa'}).click();
  await page.locator('#input-fundo-caixa').fill('100');
  await page.getByRole('button', {name:'Abrir Caixa e Entrar'}).click();
  await page.locator('.comanda-card').first().click();
  await page.getByRole('button',{name:'+ Açaí 500ml',exact:true}).click();
  await page.getByRole('button',{name:'+ Açaí 500ml',exact:true}).click();
  await page.getByRole('button',{name:'Transferir itens',exact:true}).click();
  await page.locator('#transferencia-itens input').first().fill('1');
  await page.locator('#transferencia-destino').selectOption('2');
  await page.getByRole('button',{name:'Confirmar transferência'}).click();
  assert.equal(await page.evaluate(() => comandas[1].itens.length),1);
  assert.equal(await page.evaluate(() => comandas[2].itens[0].qtd),1);
  await page.getByRole('button',{name:'Efetuar pagamento'}).click();
  await page.locator('#pag-desconto').fill('2');
  await page.locator('#pag-valor-0').fill('10');
  await page.getByRole('button',{name:'Confirmar pagamento'}).click();
  assert.match(await page.locator('#pag-erro').innerText(), /insuficiente/i);
  await page.locator('#pag-valor-0').fill('20');
  assert.match(await page.locator('#pag-troco').innerText(), /4,00/);
  await page.getByRole('button',{name:'Confirmar pagamento'}).click();
  assert.equal(await page.evaluate(() => historicoPagos[0].valor),16);
  assert.equal(await page.evaluate(() => historicoPagos[0].troco),4);
  assert.equal(await page.evaluate(() => comandas[1].aberta),false);
  await page.locator('.comanda-card').nth(1).click();
  await page.getByRole('button',{name:'Efetuar pagamento'}).click();
  await page.locator('#pag-tipo-desconto').selectOption('percentual');
  await page.locator('#pag-desconto').fill('10');
  assert.match(await page.locator('#pag-total').innerText(), /16,20/);
  await page.locator('#pag-valor-4').fill('16.20');
  assert.equal(await page.locator('#pag-cliente-box').isVisible(),true);
  await page.locator('#pag-cliente').fill('Cliente Teste');
  await page.getByRole('button',{name:'Confirmar pagamento'}).click();
  assert.equal(await page.evaluate(() => historicoPagos[0].status),'A receber');
  // Desconto vazio e pagamento em três formas, com troco só no dinheiro.
  await page.locator('.comanda-card').nth(2).click();
  await page.getByRole('button',{name:'+ Açaí 500ml',exact:true}).click();
  await page.getByRole('button',{name:'Efetuar pagamento'}).click();
  assert.equal(await page.locator('#pag-desconto').getAttribute('required'),null);
  assert.equal(await page.locator('#pag-desconto').inputValue(),'');
  await page.locator('#pag-valor-1').fill('8');
  await page.locator('#pag-valor-2').fill('5');
  await page.locator('#pag-valor-0').fill('10');
  assert.match(await page.locator('#pag-troco').innerText(),/5,00/);
  await page.getByRole('button',{name:'Confirmar pagamento'}).click();
  assert.deepEqual(await page.evaluate(()=>historicoPagos[0].pagamentos),[{metodo:'Dinheiro',valor:5},{metodo:'Pix',valor:8},{metodo:'Débito',valor:5}]);
  assert.equal(await page.evaluate(()=>historicoPagos[0].desconto),0);
  // Excedente sem dinheiro não gera troco nem fecha a comanda.
  await page.locator('.comanda-card').nth(3).click();
  await page.getByRole('button',{name:'+ Açaí 500ml',exact:true}).click();
  await page.getByRole('button',{name:'Efetuar pagamento'}).click();
  await page.locator('#pag-valor-3').fill('20');
  await page.getByRole('button',{name:'Confirmar pagamento'}).click();
  assert.match(await page.locator('#pag-erro').innerText(),/excedem/);
  await page.locator('#pag-valor-3').fill('10');
  await page.locator('#pag-valor-4').fill('8');
  await page.locator('#pag-cliente').fill('Cliente Parcial');
  await page.getByRole('button',{name:'Confirmar pagamento'}).click();
  assert.equal(await page.evaluate(()=>historicoPagos[0].status),'Parcial a receber');
  assert.equal(await page.evaluate(()=>historicoPagos[0].valorCrediario),8);
  await page.reload();
  assert.equal(await page.evaluate(() => historicoPagos.length),4);
  await page.getByRole('button',{name:'Consultar Histórico'}).click();
  await page.getByRole('cell',{name:'Cliente Teste',exact:false}).waitFor();
  await page.evaluate(() => entrarNoPDV());
  await page.locator('.comanda-card').nth(4).click();
  await page.getByRole('button',{name:'+ Açaí 500ml',exact:true}).click();
  await page.getByRole('button',{name:'Efetuar pagamento'}).click();
  await page.screenshot({path:'preview-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'preview-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),true);
  assert.deepEqual(errors,[]);
  console.log('OK: transferência, desconto opcional, descontos, pagamentos em três formas, troco, excedente inválido, crediário parcial, persistência e celular.');
  await browser.close();
})().catch(e=>{ console.error(e); process.exit(1); });

